### Note:- Python doesnot have built-in support for arrays but we use NumPy to work with python arrays 

# 1. What Are Arrays?

- An array is a special variable, which can hold more than one value at a time.

## 1. Creating An Array Object (ndarray) With .array()

In [ ]:
#using a list to create an array object

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) #here the arr is numpy.ndarray but type of np.array will be builtin function



#using a tuple to create an array object 

arr2 = np.array((10,20,30,40,50))
print(arr2)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[10 20 30 40 50]


## 2. Dimensions In Arrays

- A dimension in arrays is one level of array depth (nested arrays).

### Types Of Dimesional Arrays

- 0D Array: The elements in an array
- 1D Array: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays. 
- 2D Array: An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors
- 3D Array: An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

In [17]:
#making a 0D array 

import numpy as np

arr3 = np.array(40)
print(arr3)
print(arr3.ndim) #ndim gives no of dimensions 
print(arr3.shape) #shape gives the size along each dimension in a tuple 


#making a 1D array

arr4 = np.array([40, 10, 30])
print(arr4)
print(arr4.ndim)
print(arr4.shape) 



#making a 2D (Matrix) array 

arr5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(arr5)
print(arr5.ndim)
print(arr5.shape)


40
0
()
[40 10 30]
1
(3,)
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


## 3. Checking No'of Dimensions

- We use ndim() to check no of dimensions of arrays


In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 4. Higher Dimension Arrays 

- An array can have any number of dimensions 

- We can hardcode higher number of dimensions with ndmin(), remember its not ndim! 

In [23]:
arr6 = np.array([1,2,3,4], ndmin = 5)
print(arr6)
print("number of dimensions:", arr6.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


## 5. Indexing In Arrays

- Array indexing is just same as accessing an array element

- The first index of any array element starts from 0

In [ ]:
arr7 = np.array([20,30,40,50])
print(arr7[0])
print(arr7[1])
print(arr7[2] + arr7[3]) #doing this will cause addition of elements 

20
30
90


### Accessing 2D Arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

- Syntax: [rowindex, columnindex]


In [ ]:
#positive indexing 

arr8 = np.array([
    [1,2,3,4,5],  #row 0
    [6,7,8,9,10] #row 1
    
    ])

print(arr8[0,2])
print(arr8[1,4])
print(arr8[0,3])
print(arr8[1,2])


#negative indexing 

arr9 = np.array([
    [1,2,3,4,5],  #row 0
    [6,7,8,9,10] #row 1
    
    ])

print(arr9[0,-1])
print(arr9[1,-3])


3
10
4
8
5
8


## 6. Slicing Arrays 

In [ ]:
#positive slicing

arr10 = ([1,2,3,4,5,6,7,8,9,10])

print(arr10[1:4])
print(arr10[5:9])
print(arr10[:8])
print(arr10[6:])


#negative slicing 

print(arr10[-6:-2])
print(arr10[-8:-1])


#using step

print(arr10[1:6:2])



[2, 3, 4]
[6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8]
[7, 8, 9, 10]
[5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[2, 4, 6]


### Slicing 2D Arrays 

- Syntax: arr[row_start:row_end, col_start:col_end]

In [52]:
arr11 = np.array([
    [1, 2, 3, 4, 5],  #row 0
    [6, 7, 8, 9, 10] #row 1 
])

print(arr11[0,:]) #gives only row 0

print(arr11[1, :]) #gives only row 1

print(arr11[:, 0:3])

print(arr11[:, 3:])

print(arr11[1:, 2:4])

print(arr11[0:, 1:4])

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3]
 [6 7 8]]
[[ 4  5]
 [ 9 10]]
[[8 9]]
[[2 3 4]
 [7 8 9]]


# 7. Copy Vs View In Arrays 

- Copy: It is the new array, the copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- View: It is the view of original array, the view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view. 

In [ ]:
#demonstrating copy()

import numpy as np

arr12 = np.array([1, 2, 3, 4, 5])

x = arr12.copy() #here we have made changes in copy() that wont change original one 
arr12[0] = 100

print(arr12)
print(x)


#demostrating view()

arr13 = np.array([1, 2, 3, 4, 5])

y = arr13.view()
arr13[1] = 200

print(arr13)
print(y) #this has changed original too, coz we made changes in view()



[100   2   3   4   5]
[1 2 3 4 5]
None
[  1 200   3   4   5]
[  1 200   3   4   5]
[  1 200   3   4   5]


### Check If An Array Owns Its Data with .base

- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

In [ ]:
#demonstrating copy()

import numpy as np

arr12 = np.array([1, 2, 3, 4, 5])

x = arr12.copy() #here we have made changes in copy() that wont change original one 
arr12[0] = 100

print(arr12)
print(x)


#demostrating view()

arr13 = np.array([1, 2, 3, 4, 5])

y = arr13.view()
arr13[1] = 200

print(arr13)
print(y) #this has changed original too, coz we made changes in view()

print(x.base) #x is not changed means it owns its data
print(y.base) #y is changed means it doesnot own its data 


[100   2   3   4   5]
[1 2 3 4 5]
[  1 200   3   4   5]
[  1 200   3   4   5]
None
[  1 200   3   4   5]


# 8. Shape Of Arrays

- Shape of arrays means the number of elements in each dimension

- We use .shape for this purpose

In [13]:

arr14 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr14.shape)

arr15 = np.array([1, 2, 3, 4], ndmin=5)
print("shape of array:", arr15.shape)

(2, 4)
shape of array: (1, 1, 1, 1, 4)


# 9. Array Operations

- Joining Arrays: It can be done via stack(), hstack(), vstack()

- Splitting Arrays: It can be done via array_split(), hsplit(), vstack()

- Searching Arrays: It can be done via where()

### Joining Arrays

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [20]:
#normal stacking using stack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr = np.stack((arr16, arr17), axis = 1)
print(newarr)


#stacking along rows using hstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr2 = np.hstack((arr16, arr17))
print(newarr2)


#stacking along columns using vstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr3 = np.vstack((arr16, arr17))
print(newarr3)


#stacking along height (depth) using dstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr4 = np.dstack((arr16, arr17))
print(newarr4)



[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


### Splitting Arrays

In [ ]:
#splitting in equal numbers

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

#splitting in unequal numbers
#we cant use simple split() coz it cant adjust from the end
#thats why we use array_split() for smooth end splitting 

arr = np.array([1, 2, 3, 4, 5, 6])

newarr2 = np.array_split(arr, 4) #it will adjust from the end automatically 
print(newarr2)

#accessing elements from result

arr = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.array_split(arr, 3)

print(newarr[0]) #the subarray at 0 index 
print(newarr[1]) #the subarray at 1 index
print(newarr[2]) #the subarray at 2 index 


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]


#### Splitting 2D Arrays 

In [ ]:
#2D array containing 2 elements

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr5 = np.array_split(arr, 3)
print(newarr5)

#another 2D array containing 3 elements

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr6 = np.array_split(arr, 3)
print(newarr6)


#splitting along cloumns using hsplit()

arr = np.array([[1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9], 
    [10, 11, 12], 
    [13, 14, 15], 
    [16, 17, 18]])

newarr7 = np.hsplit(arr, 3)
print(newarr7)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

In [31]:
#searching for simple indices

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)


#searching for indices that are even 

y = np.where(arr%2 == 0)
print(y)


#searching for values that are odd

z = np.where(arr%2 == 1)
print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


#### Search Sorted

- There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- The searchsorted() method is assumed to be used on sorted arrays.

In [ ]:
#here we are using a sorted array

arr = np.array([6, 7, 8, 9])

newarr7 = np.searchsorted(arr, 7) #The number 7 should be inserted on index 1 to remain the sort order.

#The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.
print(newarr7)



1


### Searching For Multiple Values

- To search for more than one value, use an array with the specified values.

In [ ]:
#it is showing the indices where 2,4,6 should be inserted to maintain order in the array

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


### Sorting Arrays

In [ ]:
#sorting a numeric array

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


#sorting a string array

arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2))

#sorting a boolean array

arr3 = np.array([True, False, True])
print(np.sort(arr3))


[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


#### Sorting A 2D Array

- Both arrays will be sorted if we sort a 2D array

In [38]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays 

- In NumPy, you filter an array using a boolean index list.

- A boolean index list is a list of booleans corresponding to indexes in the array.

- If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [ ]:
#the boolean indexing works on a condition
#here we needed elements on index 0 and 2 thats why we kept them True

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]
