### Note:- Python doesnot have built-in support for arrays but we use NumPy to work with python arrays 

# 1. What Are Arrays?

- An array is a special variable, which can hold more than one value at a time.

## 1. Creating An Array Object (ndarray) With .array()

In [ ]:
#using a list to create an array object

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) #here the arr is numpy.ndarray but type of np.array will be builtin function



#using a tuple to create an array object 

arr2 = np.array((10,20,30,40,50))
print(arr2)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[10 20 30 40 50]


## 2. Dimensions In Arrays

- A dimension in arrays is one level of array depth (nested arrays).

### Types Of Dimesional Arrays

- 0D Array: The elements in an array
- 1D Array: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays. 
- 2D Array: An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors
- 3D Array: An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

In [17]:
#making a 0D array 

import numpy as np

arr3 = np.array(40)
print(arr3)
print(arr3.ndim) #ndim gives no of dimensions 
print(arr3.shape) #shape gives the size along each dimension in a tuple 


#making a 1D array

arr4 = np.array([40, 10, 30])
print(arr4)
print(arr4.ndim)
print(arr4.shape) 



#making a 2D (Matrix) array 

arr5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(arr5)
print(arr5.ndim)
print(arr5.shape)


40
0
()
[40 10 30]
1
(3,)
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


## 3. Checking No'of Dimensions

- We use ndim() to check no of dimensions of arrays


In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 4. Higher Dimension Arrays 

- An array can have any number of dimensions 

- We can hardcode higher number of dimensions with ndmin(), remember its not ndim! 

In [23]:
arr6 = np.array([1,2,3,4], ndmin = 5)
print(arr6)
print("number of dimensions:", arr6.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


## 5. Indexing In Arrays

- Array indexing is just same as accessing an array element

- The first index of any array element starts from 0

In [ ]:
arr7 = np.array([20,30,40,50])
print(arr7[0])
print(arr7[1])
print(arr7[2] + arr7[3]) #doing this will cause addition of elements 

20
30
90


### Accessing 2D Arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

- Syntax: [rowindex, columnindex]


In [ ]:
#positive indexing 

arr8 = np.array([
    [1,2,3,4,5],  #row 0
    [6,7,8,9,10] #row 1
    
    ])

print(arr8[0,2])
print(arr8[1,4])
print(arr8[0,3])
print(arr8[1,2])


#negative indexing 

arr9 = np.array([
    [1,2,3,4,5],  #row 0
    [6,7,8,9,10] #row 1
    
    ])

print(arr9[0,-1])
print(arr9[1,-3])


3
10
4
8
5
8


## 6. Slicing Arrays 

In [ ]:
#positive slicing

arr10 = ([1,2,3,4,5,6,7,8,9,10])

print(arr10[1:4])
print(arr10[5:9])
print(arr10[:8])
print(arr10[6:])


#negative slicing 

print(arr10[-6:-2])
print(arr10[-8:-1])


#using step

print(arr10[1:6:2])



[2, 3, 4]
[6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8]
[7, 8, 9, 10]
[5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[2, 4, 6]


### Slicing 2D Arrays 

- Syntax: arr[row_start:row_end, col_start:col_end]

In [52]:
arr11 = np.array([
    [1, 2, 3, 4, 5],  #row 0
    [6, 7, 8, 9, 10] #row 1 
])

print(arr11[0,:]) #gives only row 0

print(arr11[1, :]) #gives only row 1

print(arr11[:, 0:3])

print(arr11[:, 3:])

print(arr11[1:, 2:4])

print(arr11[0:, 1:4])

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3]
 [6 7 8]]
[[ 4  5]
 [ 9 10]]
[[8 9]]
[[2 3 4]
 [7 8 9]]
