### Note:- Python doesnot have built-in support for arrays but we use NumPy to work with python arrays 

# 1. What Are Arrays?

- An array is a special variable, which can hold more than one value at a time.

## 1. Creating NumPy Arrays

### With Python Objects (list, tuple):

In [111]:
#using a python object, list to create an array object

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) #here the arr is numpy.ndarray object but type of np.array will be builtin function

listarr = np.array([[1,2,3], [5,8,5], [0,3,1]])
print(listarr)
print(listarr.dtype)
print(listarr.shape)
print(listarr.size)

#using a python object, tuple to create an array object 

arr2 = np.array((10,20,30,40,50))
print(arr2)



[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [5 8 5]
 [0 3 1]]
int64
(3, 3)
9
[10 20 30 40 50]


### With Intrinsic Objects: 

- We can use arange, ones, zeroes to make arrays with NumPy intrinsic objects

In [112]:
#creating an array with np.zeroes()

zeroes = np.zeros((2,5))
print(zeroes)
print(zeroes.dtype)
print(zeroes.shape)
print(zeroes.size)

#creating an array with np.ones()

ones = np.ones((2,6))
print(ones)
print(ones.dtype)
print(ones.shape)
print(ones.size)


#creating an array with np.arange() 

rng = np.arange(15)
print(rng)
print(rng.dtype)
print(rng.shape) #it gives here 15, coz NumPy returns arrays as tuples, so its telling its a tuple array not number 15
print(rng.size)


#creating an array using np.linspace()

lsp = np.linspace(1,5,12) #the range of number will be 1-5 but the elements will be 12 but equally linear spaced
print(lsp)
print(lsp.dtype)
print(lsp.shape)
print(lsp.size)

lsp2 = np.linspace(1,50,10) #the range will be 1-50 but the elements will be 10
print(lsp2)


#creating an array with np.empty()

emp = np.empty((1,5)) #gives garbage values available in the memory, faster than np.zeros, np.ones 
print(emp)


#creating an array with np.reshape()

arr3 = np.arange(20) #gives normal range of numbers from 0 to 19
print(arr3)

newarr3 = arr3.reshape(5,4) #reshapes the array with 5 rows and columns and it gives view of an array 
print(newarr3)

#creating an array with np.full()

arr4 = np.full((2,2),7) #it takes the shape and the number that we want to fill our matrix with
print(arr4)

#creating an identity matrix using np.eye()

arr5 = np.eye(3) #gives a 3x3 matrix by default 
print(arr5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)
10
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
float64
(2, 6)
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int64
(15,)
15
[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]
float64
(12,)
12
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]
[[0.e+000 1.e-323 1.e-323 5.e-324 5.e-324]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Attributes:

- They give us more information about arrays

- arr.shape: gives the number of rows and columns in array

- arr.size: gives total number of elements in array

- arr.ndim: give the dimension of arrays 

- arr.dtype: gives datatype of elements in arrays

## Changing DataType Of Arrays With .astype()


In [113]:
#changing float to int

myarr2 = np.array([2.4, 5.8, 12.54])
print(myarr2)
print(myarr2.dtype) #bfr conversion

newarr2 = myarr2.astype(int)
print(newarr2)
print(newarr2.dtype) #after conversion

[ 2.4   5.8  12.54]
float64
[ 2  5 12]
int64


## Aggregation Function Of Arrays

- np.sum(): sums all arrays

- np.mean(): gives average of arrays

- np.min(): gives smallest number of arrays

- np.max(): gives maximum number of arrays 

- np.std(): calcualtes standard deriviation of arrays

- np.var(): calcualtes variance of arrays 

In [114]:
myarr3 = np.array([10,20,30,40,50])

#finding sum 

print(np.sum(myarr3))

#finding mean

print(np.mean(myarr3))

#finding max 

print(np.max(myarr3))

#finding min

print(np.min(myarr3))

#finding standard derviation

print(np.std(myarr3))

#finding variance 

print(np.var(myarr3))

150
30.0
50
10
14.142135623730951
200.0


## 2. Dimensions In Arrays

- A dimension in arrays is one level of array depth (nested arrays).

### Types Of Dimesional Arrays

- 0D Array: The elements in an array
- 1D Array: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays. 
- 2D Array: An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors
- 3D Array: An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

In [115]:
#making a 0D array 

import numpy as np

arr3 = np.array(40)
print(arr3)
print(arr3.ndim) #ndim gives no of dimensions 
print(arr3.shape) #shape gives the size along each dimension in a tuple 


#making a 1D array

arr4 = np.array([40, 10, 30])
print(arr4)
print(arr4.ndim)
print(arr4.shape) 



#making a 2D (Matrix) array 

arr5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(arr5)
print(arr5.ndim)
print(arr5.shape)


40
0
()
[40 10 30]
1
(3,)
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


## 3. Checking No'of Dimensions

- We use ndim() to check no of dimensions of arrays


In [116]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 4. Higher Dimension Arrays 

- An array can have any number of dimensions 

- We can hardcode higher number of dimensions with ndmin(), remember its not ndim! 

In [117]:
arr6 = np.array([1,2,3,4], ndmin = 5)
print(arr6)
print("number of dimensions:", arr6.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


### Analysis Of Arrays

- Indexing & Fancy Indexing: to access 1 element in rows/columns

- Boolean Masking: to apply a condition on the elements in rows/columns 

- Slicing: to access multiple elements in rows/columns

## 5. Indexing In Arrays

- Array indexing is just same as accessing an array element

- The first index of any array element starts from 0

In [118]:
arr7 = np.array([20,30,40,50])
print(arr7[0])
print(arr7[1])
print(arr7[2] + arr7[3]) #doing this will cause addition of elements 

20
30
90


### Fancy Indexing

- Selecting multiple elements at once

In [119]:
#accessing multiple elements with fancy indexing
#we must pass a list to access multiple elements [[]]

myarr4 = np.array([10, 20, 30, 40, 50, 60])
print(myarr4[[0,2,4]])

[10 30 50]


## Boolean Masking/Filtering Data On Basis Of A Condtition 

- We can filter desired data with the help of boolean masking by applying a condition

In [120]:
#here we will apply conditions using boolean masking

myarr5 = np.array([10, 20, 30, 40, 50, 60])

#gives elements greater than 25 

print(myarr5[myarr5>25])

#gives elements smaller than 40 

print(myarr5[myarr5<40])

[30 40 50 60]
[10 20 30]


### Accessing 2D Arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

- Syntax: [rowindex, columnindex]


### Concept Of Axis In Accessing 

- Rows: Axis 0 means if axis is 0 all the operations will be done along column elements

- Columns: Axis 1 means if axis is 1 all the operations will be done along row elements

- Remember:

- 1D arrays have only axis 0 means only rows 

- 2D arrays have both axis 0 and axis 1 

In [121]:
import numpy as np 

x = [[1,2,3], 
     [4,5,6], 
     [7,1,0]]

myarr = np.array(x)
print(myarr)

myarr.sum(axis=0) #it has summed the column elements 
myarr.sum(axis=1) #it has summed the row elements 

myarr.T #it has transposed the array

myarr.argmax() #gives max element in array
myarr.argmax(axis=0)
myarr.argmin() #gives min element in array
myarr.argsort() #gives the indices if the elements were at these indices, they would have been sorted 
myarr.argmax(axis=0) #check max elements along columns
myarr.argmin(axis=1) #checks min elements along rows 
myarr.ravel() #it ravels the elements in a line 
myarr.reshape(9,1)


[[1 2 3]
 [4 5 6]
 [7 1 0]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [122]:
#positive indexing 

arr8 = np.array([
    [1,2,3,4,5],  #row 0 
    [6,7,8,9,10] #row 1 
    
    ])

print(arr8[0,2])
print(arr8[1,4])
print(arr8[0,3])
print(arr8[1,2])


#negative indexing 

arr9 = np.array([
    [1,2,3,4,5],  #row 0
    [6,7,8,9,10] #row 1
    
    ])

print(arr9[0,-1])
print(arr9[1,-3])


3
10
4
8
5
8


### Accessing And Changing An Array

- We can simply access and change elements in an array 


In [123]:
import numpy as np

#using python object: list

arr1 = np.array([[1,2,3,4,5]])

arr1[0,1] = 100 #it means change the number at 0 row and 1 column with 100
print(arr1)

[[  1 100   3   4   5]]


## 6. Slicing Arrays 

In [124]:
#positive slicing

arr10 = ([1,2,3,4,5,6,7,8,9,10])

print(arr10[1:4])
print(arr10[5:9])
print(arr10[:8])
print(arr10[6:])


#negative slicing 

print(arr10[-6:-2])
print(arr10[-8:-1])


#using step

print(arr10[1:6:2])



[2, 3, 4]
[6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8]
[7, 8, 9, 10]
[5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[2, 4, 6]


### Slicing 2D Arrays 

- Syntax: arr[row_start:row_end, col_start:col_end]

In [125]:
arr11 = np.array([
    [1, 2, 3, 4, 5],  #row 0
    [6, 7, 8, 9, 10] #row 1 
])

print(arr11[0,:]) #gives only row 0

print(arr11[1, :]) #gives only row 1

print(arr11[:, 0:3])

print(arr11[:, 3:])

print(arr11[1:, 2:4])

print(arr11[0:, 1:4])

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3]
 [6 7 8]]
[[ 4  5]
 [ 9 10]]
[[8 9]]
[[2 3 4]
 [7 8 9]]


## Flattening Arrays

- Flattening means converting a multi-dimensional array (2D, 3D, etc.) into a 1D array.

- Useful when you want to process all elements linearly or feed data into ML models.

### Important Concepts:

- np.flatten(): gives copy

- np.ravel(): gives view

In [126]:
myarr6 = np.array([[1,2,3], [4,5,6]])

print(myarr6.ravel()) #gives view 

print(myarr6.flatten()) #gives copy

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# 7. Copy Vs View In Arrays 

- Copy: It is the new array, the copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- View: It is the view of original array, the view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view. 

In [127]:
#demonstrating copy()

import numpy as np

arr12 = np.array([1, 2, 3, 4, 5])

x = arr12.copy() #here we have made changes in copy() that wont change original one 
arr12[0] = 100

print(arr12)
print(x)


#demostrating view()

arr13 = np.array([1, 2, 3, 4, 5])

y = arr13.view()
arr13[1] = 200

print(arr13)
print(y) #this has changed original too, coz we made changes in view()



[100   2   3   4   5]
[1 2 3 4 5]
[  1 200   3   4   5]
[  1 200   3   4   5]


### Check If An Array Owns Its Data with .base

- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

In [128]:
#demonstrating copy()

import numpy as np

arr12 = np.array([1, 2, 3, 4, 5])

x = arr12.copy() #here we have made changes in copy() that wont change original one 
arr12[0] = 100

print(arr12)
print(x)


#demostrating view()

arr13 = np.array([1, 2, 3, 4, 5])

y = arr13.view()
arr13[1] = 200

print(arr13)
print(y) #this has changed original too, coz we made changes in view()

print(x.base) #x is not changed means it owns its data
print(y.base) #y is changed means it doesnot own its data 


[100   2   3   4   5]
[1 2 3 4 5]
[  1 200   3   4   5]
[  1 200   3   4   5]
None
[  1 200   3   4   5]


# 8. Shape Of Arrays

- Shape of arrays means the number of elements in each dimension

- We use .shape for this purpose

- Or in other words: shape gives number of rows and columns

In [129]:

arr14 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr14.shape)

arr15 = np.array([1, 2, 3, 4], ndmin=5)
print("shape of array:", arr15.shape)

(2, 4)
shape of array: (1, 1, 1, 1, 4)


# 9. Array Operations

- Joining Arrays: It can be done via stack(), hstack(), vstack()

- Splitting Arrays: It can be done via array_split(), hsplit(), vstack()

- Searching Arrays: It can be done via where()

- Inserting In Arrays: It can be done via insert()

### Joining Arrays

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [130]:
#normal stacking using stack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

ar2 = np.concatenate([arr16, arr17]) #concatenates the arrays 
print(ar2)

newarr = np.stack((arr16, arr17), axis = 1)
print(newarr)


#stacking along rows using hstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr2 = np.hstack((arr16, arr17))
print(newarr2)


#stacking along columns using vstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr3 = np.vstack((arr16, arr17))
print(newarr3)


#stacking along height (depth) using dstack()

arr16 = np.array([1, 2, 3])

arr17 = np.array([4, 5, 6])

newarr4 = np.dstack((arr16, arr17))
print(newarr4)



[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


### Splitting Arrays

In [131]:
#splitting in equal numbers

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

#splitting in unequal numbers
#we cant use simple split() coz it cant adjust from the end
#thats why we use array_split() for smooth end splitting 

arr = np.array([1, 2, 3, 4, 5, 6])

newarr2 = np.array_split(arr, 4) #it will adjust from the end automatically 
print(newarr2)

#accessing elements from result

arr = np.array([1, 2, 3, 4, 5, 6])

newarr3 = np.array_split(arr, 3)

print(newarr[0]) #the subarray at 0 index 
print(newarr[1]) #the subarray at 1 index
print(newarr[2]) #the subarray at 2 index 


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]


#### Splitting 2D Arrays 

In [132]:
#2D array containing 2 elements

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr5 = np.array_split(arr, 3)
print(newarr5)

#another 2D array containing 3 elements

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr6 = np.array_split(arr, 3)
print(newarr6)


#splitting along cloumns using hsplit()

arr = np.array([[1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9], 
    [10, 11, 12], 
    [13, 14, 15], 
    [16, 17, 18]])

newarr7 = np.hsplit(arr, 3)
print(newarr7)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

In [133]:
#searching for simple indices

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)


#searching for indices that are even 

y = np.where(arr%2 == 0)
print(y)


#searching for values that are odd

z = np.where(arr%2 == 1)
print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


#### Search Sorted

- There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- The searchsorted() method is assumed to be used on sorted arrays.

In [134]:
#here we are using a sorted array

arr = np.array([6, 7, 8, 9])

newarr7 = np.searchsorted(arr, 7) #The number 7 should be inserted on index 1 to remain the sort order.

#The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.
print(newarr7)



1


### Searching For Multiple Values

- To search for more than one value, use an array with the specified values.

In [135]:
#it is showing the indices where 2,4,6 should be inserted to maintain order in the array

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


### Inserting In Arrays

- np.insert takes (name of old arr, index number of old number, new number, axis if desired)

In [136]:
#inserting with 1D array

ar = np.array([10, 20, 30, 40, 50, 60])
print(ar)

newar = np.insert(ar, 2, 100, axis=0) 
print(newar)


#inserting with 2D arrays

ar1 = np.array([[1,2], [3,4]])
print(ar1)

#now insert a new row at index 1

newar1 = np.insert(ar1, 1, [5,6], axis=0) #inserts [5,6] after [1,2] at index 1 now in row coz of axis=0
print(newar1)
newar1 = np.insert(ar1, 1, [7,8], axis=1) #inserts [7,8] after [1,3] at index 1 now in column coz of axis=1
print(newar1)
newar1 = np.insert(ar1, 1, [7,8], axis=None) #flattens the array coz of axis=None
print(newar1)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]
[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]
[[1 7 2]
 [3 8 4]]
[1 7 8 2 3 4]


### Sorting Arrays

In [137]:
#sorting a numeric array

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


#sorting a string array

arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2))

#sorting a boolean array

arr3 = np.array([True, False, True])
print(np.sort(arr3))


[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


#### Sorting A 2D Array

- Both arrays will be sorted if we sort a 2D array

In [138]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filtering Arrays 

- In NumPy, you filter an array using a boolean index list.

- A boolean index list is a list of booleans corresponding to indexes in the array.

- If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [139]:
#the boolean indexing works on a condition
#here we needed elements on index 0 and 2 thats why we kept them True

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


## 10. Broadcasting & Vectorization In Arrays

- Broadcasting: NumPy automatically expands smaller arrays to larger arrays so shapes match.

- Vectorization: Doing operations on whole arrays without loops at once, easy to apply on matrix ops

### 1. Rules Of Broadcasting 

- Matching Dimensions 

- Eg: [1,2,3] + [4,5,6] = [5,7,9]

- Expanding Single Elements 

- Eg: [1,2,3] + 10 = [11,12,13]

- Incompatible Shapes

- Eg: [1,2,3] + [1,2] -> gives value error coz shapes are different 

In [142]:
#broadcasting concept

a = np.array([1,2,3])
print(a+5)


prices = np.array([100, 200, 300])
discount = 10 #this is scalar 

finalprices = prices - (prices*discount/100)
print(finalprices)

[6 7 8]
[ 90. 180. 270.]


In [143]:
#vectorization concept
#fast C Loop arithmetical ops

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)


ar3 = np.array([10,20,30])
multiplied = ar3*5
print(multiplied)

[5 7 9]
[ 50 100 150]


## 11. Handling Missing Values

- np.isnan()

- np.nan_to_num()

- np.isinf()

## (A) Finding Missing Values

### 1. np.isnan()

- It is a NumPy function that checks whether each element in an array is NaN (Not a Number).

- Returns True for values that are NaN

- Returns False for all other numbers

In [ ]:
#true means that there are missing values present at these indices 
#we cannot compare NaN values 

ar4 = np.array([1,2,np.nan, 3, 4, np.nan, 5,6, np.nan])
print(np.isnan(ar4)) 

[False False  True False False  True False False  True]


## (B) Converting Missing Values To Numbers

### 2. np.nan_to_num()

- It converts a missing value to a number that we specify, default value is 0 always

In [146]:
#using default value 0

ar5 = np.array([1, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan])

cleanar5 = np.nan_to_num(ar5)
print(cleanar5)

#using a specified value nan=100

cleanar5 = np.nan_to_num(ar5, nan=100)
print(cleanar5)

[1. 2. 0. 3. 4. 0. 5. 6. 0.]
[  1.   2. 100.   3.   4. 100.   5.   6. 100.]


## (C) Finding Infinite Values


### 3. np.isinf()

- It checks whether there are infinite values in data 

- Infinite values can be 1/0, np.inf, -np.inf

In [147]:
ar6 = np.array([1, 2, -np.inf, 3, 4, 5, 6, np.inf, 7, 8])
print(np.isinf(ar6))

[False False  True False False False False  True False False]


## (D) Converting Infinite Values To Finite Ones


### 4. np.nan_to_num()

In [152]:
ar7 = np.array([1, 2, -np.inf, 3, 4, 5, 6, np.inf, 7, 8])
print(ar7)

cleanar7 = np.nan_to_num(ar7, posinf=1000, neginf=-1000)
print(cleanar7)

[  1.   2. -inf   3.   4.   5.   6.  inf   7.   8.]
[    1.     2. -1000.     3.     4.     5.     6.  1000.     7.     8.]
