# 1. NumPy Practice Session One

- Here, I am going to practice core NumPy Array concepts + syntax 

In [27]:
import numpy as np

#Q:1 Create a 6×6 matrix with random integers between 1 and 20

arr1 = np.random.randint(1,21, size=(6,6))
print(arr1, np.shape(arr1))


#Q:2 Select all multiples of 3 from an array

arr2 = np.array([3, 7, 9, 10, 12, 14, 18])

newarr2 = arr2[arr2%3==0]
print(newarr2)


#Q:3 Replace all numbers less than 10 with 0

arr3 = np.array([5, 12, 3, 20, 7, 15])

arr3[arr3<10] = 0
print(arr3)


#Q:4 Horizontally stack two 2×3 arrays

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])

c = np.vstack((a,b))
print(c)

#Q:5 Flatten a 4×3 matrix and reverse it

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

newmat = mat.flatten()[::-1]
print(newmat)

newmat2 = np.flip(mat)
print(newmat2)

[[16 18  9 19  3  8]
 [ 2 11  7 16 12 12]
 [19  2 16  6 15  2]
 [10 11  4 13  5 20]
 [12 17  4 11 15 17]
 [ 5 13 15 18 13  3]] (6, 6)
[ 3  9 12 18]
[ 0 12  0 20  0 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[12 11 10  9  8  7  6  5  4  3  2  1]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


## NumPy Pattern Recognition

- Indexing & Slicing: Row and column extraction using slicing and indices, Mental shortcut: “arr[row_index, :] → row, arr[:, col_index] → column”

- Boolean Masking: Filter elements based on condition using Boolean masks, Mental shortcut: “arr[condition] → select elements matching condition”

- Aggregate Operations: Sum of all elements, sum along rows or columns using axis, Mental shortcut: “axis=0 → column-wise, axis=1 → row-wise”

In [28]:
import numpy as np

#Q1 Create a 3×4 NumPy array with random integers between 1 and 20.Print the array, its shape, and its data type

arrr = np.random.randint(1,20, size=(3,4))
print(arrr, np.shape(arrr))
print(arrr.dtype)


#Q:2 Extract the second row and last column separately.

arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print(arr[1])
print(arr[:, 2])


#Q:3 Create a new array containing only numbers greater than 5.

arr = np.array([3, 7, 2, 9, 4, 8, 1])

newarr = arr[arr>5]
print(newarr)


#Q:4 Compute the sum of all elements, and the sum of each column separately.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

sumarr = np.sum(arr)
print(sumarr)

colsum = np.sum(arr, axis=1)
print(colsum)


#Q:5(a) Compute a new array which is arr2 - arr1 (element-wise subtraction)
#Q:5(b) Compute another array arr1 * arr2 (element-wise multiplication)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

sub = arr2 - arr1
print(sub)

mult = arr1 * arr2
print(mult)

[[11  2 17 14]
 [ 8 17  7 10]
 [11 17 14 18]] (3, 4)
int32
[20 25 30]
[15 30 45]
[7 9 8]
45
[ 6 15 24]
[ 9 18 27 36]
[ 10  40  90 160]
