# 1. NumPy Practice Session One

- Here, I am going to practice core NumPy Array concepts + syntax 

In [13]:
import numpy as np

#Q:1 Create a 6×6 matrix with random integers between 1 and 20

arr1 = np.random.randint(1,21, size=(6,6))
print(arr1, np.shape(arr1))


#Q:2 Select all multiples of 3 from an array

arr2 = np.array([3, 7, 9, 10, 12, 14, 18])

newarr2 = arr2[arr2%3==0]
print(newarr2)


#Q:3 Replace all numbers less than 10 with 0

arr3 = np.array([5, 12, 3, 20, 7, 15])

arr3[arr3<10] = 0
print(arr3)


#Q:4 Horizontally stack two 2×3 arrays

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])

c = np.vstack((a,b))
print(c)

#Q:5 Flatten a 4×3 matrix and reverse it

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

newmat = mat.flatten()[::-1]
print(newmat)

newmat2 = np.flip(mat)
print(newmat2)

[[20  4 14 18  3  6]
 [ 1  3 12  7 20  9]
 [ 7  7 16  2 13  8]
 [ 3  2  6  2 20 10]
 [ 4  4 17  1 20 11]
 [10  8  1 19 13  5]] (6, 6)
[ 3  9 12 18]
[ 0 12  0 20  0 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[12 11 10  9  8  7  6  5  4  3  2  1]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]
