# 1. NumPy Practice Session: Day 1

- Here, I am going to practice core NumPy Array concepts + syntax 

In [122]:
import numpy as np

#Q:1 Create a 6×6 matrix with random integers between 1 and 20

arr1 = np.random.randint(1,21, size=(6,6))
print(arr1, np.shape(arr1))


#Q:2 Select all multiples of 3 from an array

arr2 = np.array([3, 7, 9, 10, 12, 14, 18])

newarr2 = arr2[arr2%3==0]
print(newarr2)


#Q:3 Replace all numbers less than 10 with 0

arr3 = np.array([5, 12, 3, 20, 7, 15])

arr3[arr3<10] = 0
print(arr3)


#Q:4 Horizontally stack two 2×3 arrays

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])

c = np.vstack((a,b))
print(c)

#Q:5 Flatten a 4×3 matrix and reverse it

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

newmat = mat.flatten()[::-1]
print(newmat)

newmat2 = np.flip(mat)
print(newmat2)

[[17  5 12  4 10  2]
 [ 2  7  3  5  3 10]
 [ 9 15 17  1  6 13]
 [ 9  5 12  7 17  2]
 [20  8  3  1  9  4]
 [ 6 15 19 20  9 20]] (6, 6)
[ 3  9 12 18]
[ 0 12  0 20  0 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[12 11 10  9  8  7  6  5  4  3  2  1]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


## NumPy Pattern Recognition

- Indexing & Slicing: Row and column extraction using slicing and indices, Mental shortcut: “arr[row_index, :] → row, arr[:, col_index] → column”

- Boolean Masking: Filter elements based on condition using Boolean masks, Mental shortcut: “arr[condition] → select elements matching condition”

- Aggregate Operations: Sum of all elements, sum along rows or columns using axis, Mental shortcut: “axis=0 → column-wise, axis=1 → row-wise”

In [123]:
import numpy as np

#Q1 Create a 3×4 NumPy array with random integers between 1 and 20.Print the array, its shape, and its data type

arrr = np.random.randint(1,20, size=(3,4))
print(arrr, np.shape(arrr))
print(arrr.dtype)


#Q:2 Extract the second row and last column separately.

arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

print(arr[1])
print(arr[:, 2])


#Q:3 Create a new array containing only numbers greater than 5.

arr = np.array([3, 7, 2, 9, 4, 8, 1])

newarr = arr[arr>5]
print(newarr)


#Q:4 Compute the sum of all elements, and the sum of each column separately.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

sumarr = np.sum(arr)
print(sumarr)

colsum = np.sum(arr, axis=1)
print(colsum)


#Q:5(a) Compute a new array which is arr2 - arr1 (element-wise subtraction)
#Q:5(b) Compute another array arr1 * arr2 (element-wise multiplication)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

sub = arr2 - arr1
print(sub)

mult = arr1 * arr2
print(mult)

[[ 4 14 14  7]
 [19 15 13 16]
 [17 15  6 14]] (3, 4)
int32
[20 25 30]
[15 30 45]
[7 9 8]
45
[ 6 15 24]
[ 9 18 27 36]
[ 10  40  90 160]


# 2. NumPy Practice Session: Day 2

- Proving that numpy arrays are faster than python lists for ops 
- Difference between vector, matrix, tensor 
- Creating arrays with python objects 
- Creating arrays with intrinsic objects 
- Array Attributes/Properties 
- Checking Compatibility of arrays based on shapes
- Changing datatype of arrays with astype()
- Aggregation functions
- Dimensions 
- Checking number of dimensions
- Boolean Masking 
- Indexing/Fancy Indexing
- Accessing 2D Arrays
- Types of 2D Array Indexing (Positive, Negative)
- Changing Arrays Through Indexing 
- Slicing 1D Arrays
- Slicing 2D Arrays
- Flattening Arrays (np.flatten(), np.ravel())
- Shape Of Arrays
- Array Operations (joining/stacking, splitting, searching, inserting)
- Broadcasting
- Vectorization
- Handling missing values (np.isnan, np.isinf, np.nan_to_num)



In [124]:
import numpy as np
import time

#adding two python lists

size = 1_00_000
list1 = list(range(size))
list2  = list(range(size))

start = time.time()
result = [x+y for x,y in zip(list1, list2)]
end = time.time()

print("python list addition:", end - start)


#adding two numpy arrays

size = 1_00_000
ar1 = np.array(list1)
ar2 = np.array(list2)

start = time.time()
result2 = ar1 + ar2
end = time.time()

print("numpy arrays addition time:", end - start)


vector = np.array([1,2,3])
print("this is a vector:", vector)

matrx = np.array([[1,2,3], 
                 [4,5,6]])
print("this is a matrix:", matrx)

tensr = np.array([[[1,2], [3,4]]])
print(tensr)

pylist = [1,2,3,4,5,6,7]
ar = np.array(pylist)
print(ar)
print(ar.dtype)


zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((4,3))
print(ones)

ident = np.eye(5,5)
print(ident)

rnge = np.arange(10)
print(rnge)


ar3 = np.random.randint(0,10, size=(5,3))
print(ar3)

lsp = np.linspace(1, 50, 9)
print(lsp)

rnge2 = np.arange(25)
print(rnge2)

newrnge = rnge2.reshape((5,5))
print(newrnge)

ar4 = np.full((3,3), 10)
print(ar4)

myar = np.array([1,2,3,4])

print(myar.shape)
print(myar.dtype)
print(myar.size)

myar2 = np.array([[1,2,3], 
                 [4,5,6]])
print(myar2.shape)
print(myar2.dtype)
print(myar2.size)

python list addition: 0.014256715774536133
numpy arrays addition time: 0.00044846534729003906
this is a vector: [1 2 3]
this is a matrix: [[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]]
[1 2 3 4 5 6 7]
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[[7 4 6]
 [1 3 8]
 [4 7 4]
 [6 8 7]
 [4 8 7]]
[ 1.     7.125 13.25  19.375 25.5   31.625 37.75  43.875 50.   ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
(4,)
int64
4
(2, 3)
int64
6


In [125]:
a = np.array([1,2,3])
b = np.array([6,7,8,9])
c = np.array([1,2])
d = np.array([4,5,6])
e = np.array([8,9])

print(a.shape == b.shape)
print(a.shape == d.shape)
print(c.shape == e.shape)
print(c.shape == a.shape)


ary = np.array([2.3, 4.5, 32.45, 67.23])
print(ary.dtype)

newary = ary.astype(int)
print(newary.dtype)


ary1 = np.array([2,20, 34, 56, 12, 98, 67])
print(np.sum(ary1))

print(np.mean(ary1))

print(np.min(ary1))

print(np.max(ary1))

print(np.std(ary1))

print(np.var(ary1))

ary2 = np.array(10)
print(ary2)
print(ary2.dtype)
print(ary2.shape)
print(ary2.ndim)

ary3 = np.array([10,20,30,50,36])
print(ary3)
print(ary3.dtype)
print(ary3.shape)
print(ary3.ndim)


ary4 = np.array([[1.9,2.4,3.8],
                 [4.5,5.2,6.4]])
print(ary4.dtype)
print(ary4.shape)
print(ary4.ndim)


ars = np.array(5)
ars1 = np.array([1,2,3])
ars2 = np.array([[1,2,3], [4,5,6]])
ars3 = np.array([[[1,2], [3,4]]])

print(ars.ndim)
print(ars1.ndim)
print(ars2.ndim)
print(ars3.ndim)

False
True
True
False
float64
int64
289
41.285714285714285
2
98
31.626003251006175
1000.2040816326531
10
int64
()
0
[10 20 30 50 36]
int64
(5,)
1
float64
(2, 3)
2
0
1
2
3


In [126]:
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar[4])
print(ar[6])

ar1 = np.array([20,30,40,50,60])
print(ar1[[2,3,4]])

ar3 = np.array([1,2,3,4,5])

ar3 = ar3[np.isin(ar3,[2,3,4])]
print(ar3)


x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


x.argmin(axis=1)

x.argsort()

x.ravel()
x.flatten()

5
7
[40 50 60]
[2 3 4]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
import numpy as np

ar = np.array([[1,2,3,4,5],
       [6,7,8,9,10]])

print(ar[0,0])
print(ar[1,3])
print(ar[0,4])
print(ar[1,2])

ar2 = np.array([[1,2,3], 
                [5,6,7]])

ar2[1,2] = 2000
print(ar2)

ar2[0, 1] = 5000
print(ar2)

ar3 = np.array([1,2,3,4,5,6,7,8,9])

print(ar3[5:])
print(ar3[:-1])
print(ar3[::-1])
print(ar3[-7:-2])
print(ar3[:-4])


ar4 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print(ar4[0, :])
print(ar4[1, :])
print(ar4[0, 1:4])
print(ar4[0, :4])
print(ar4[1, ::-1])
print(ar4[1, -5:-2])



1
9
5
8
[[   1    2    3]
 [   5    6 2000]]
[[   1 5000    3]
 [   5    6 2000]]
[6 7 8 9]
[1 2 3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1]
[3 4 5 6 7]
[1 2 3 4 5]
[1 2 3 4 5]
[ 6  7  8  9 10]
[2 3 4]
[1 2 3 4]
[10  9  8  7  6]
[6 7 8]


In [128]:
import numpy as np

ar = np.array([[1,2,3],
              [4,5,6]])

print(ar.flatten()) #copy mein changes kiye hain original mein nhi kiye 
print(ar)

newar = ar.copy()

newar[0,0] = 5000

print(ar)
print(newar)


ar2 = np.array([[20, 30, 40],
                [50, 60, 70]])

newar2 = ar2.view()
newar2[1, 1] = 87

print(ar2)
print(newar2)



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[5000    2    3]
 [   4    5    6]]
[[20 30 40]
 [50 87 70]]
[[20 30 40]
 [50 87 70]]


In [129]:
import numpy as np

#proving that flatten gives copy

arr = np.array([[1,2,3], [4,5,6]])

newarr = arr.flatten()
newarr[0] = 5000

print(newarr) #the original array does not change with changes made in new array 
print(arr)


#proving that ravel gives view

arr2 = np.array([[10, 20, 30], [40, 50, 60]])

newarr2 = arr2.ravel()
newarr2[1] = 4870

print(newarr2) #the original array also changes with changes made in new array
print(arr2)

[5000    2    3    4    5    6]
[[1 2 3]
 [4 5 6]]
[  10 4870   30   40   50   60]
[[  10 4870   30]
 [  40   50   60]]


In [130]:
#shape of arrays give the number of elements in an array

ar = np.array([[1,2,3], [4,5,6]])
print(np.shape(ar))


ar1 = np.array([1,2,3,4], ndmin = 5)
print(ar1.shape)

(2, 3)
(1, 1, 1, 1, 4)


In [139]:
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

ar3 = np.concatenate([ar1, ar2])
print(ar3)

ar4 = np.stack((ar1, ar2), axis=1)
print(ar4)

ar5 = np.vstack((ar1, ar2)) #happens row wise
print(ar5)

ar6 = np.hstack((ar1, ar2))
print(ar6)

ar7 = np.dstack((ar1, ar2))
print(ar7)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [168]:
ar = np.array([[1,2,3,4],
               [5,6,7,8]])

newar = np.split(ar, 2, axis=1)
print(newar)

newar2 = np.hsplit(ar, 2)
print(newar2)

newar3 = np.vsplit(ar, 2)
print(newar3)


arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 3)
print(x)


myar = np.array([10, 20, 30, 40, 50, 60])

newmyar = np.insert(myar, 3, 5000, axis=0)
print(newmyar)

myar2 = np.array([[1,2], [3,4]])
newmyar2 = np.insert(myar2, 1, [400, 500], axis=1)
print(newmyar2)

newmyar3 = np.insert(myar2, 1, [400, 500], axis=0)
print(newmyar3)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
(array([2]),)
[  10   20   30 5000   40   50   60]
[[  1 400   2]
 [  3 500   4]]
[[  1   2]
 [400 500]
 [  3   4]]


In [ ]:
#broadcasting 

ar = np.array([1,2,3,4,5,6,7])
print(ar+50)


ar1 = np.array([1,2,3])

x = ar1 + 10
print(x)



[51 52 53 54 55 56 57]
[11 12 13]


In [ ]:
#step1: finding missing values: we use np.isnan()

ar4 = np.array([1,2,np.nan, 3, 4, np.nan, 5,6, np.nan])
print(np.isnan(ar4))


#step2: converting missing values to numbers: np.nan_to_num()

ar5 = np.array([1, 2, np.nan, 3, 4, np.nan, 5, 6, np.nan])
cleanedar5 = np.nan_to_num(ar5, nan=500)
print(cleanedar5)


#step3: finding infinite values: we use np.isinf()

ar6 = np.array([1, 2, -np.inf, 3, 4, 5, 6, np.inf, 7, 8])
cleanedar6 = np.isinf(ar6)
print(cleanedar6)



[False False  True False False  True False False  True]
[  1.   2. 500.   3.   4. 500.   5.   6. 500.]
[False False  True False False False False  True False False]


In [178]:
ar = np.array([1,2, np.nan, 3,4,5, np.nan])
cleanedar = np.isnan(ar)
print(cleanedar)

ar1 = np.array([1,2, np.nan, 3,4,5, np.nan])
cleanedar1 = np.nan_to_num(ar1, nan=200)
print(cleanedar1)

ar2 = np.array([1,2, np.inf, 3,4,5, np.inf])
cleanedar2 = np.isinf(ar2)
print(cleanedar2)

ar3 = np.array([1,2, np.inf, 3,4,5, np.inf])
cleanedar3 = np.nan_to_num(ar3, posinf = 1000, neginf = -1000)
print(cleanedar3)

[False False  True False False False  True]
[  1.   2. 200.   3.   4.   5. 200.]
[False False  True False False False  True]
[   1.    2. 1000.    3.    4.    5. 1000.]
