# What Are UFuncs For Arrays?

- Ufuncs are called universal functions that are implemented on NumPy ndarray object 

## 1. Purpose Of Ufuncs

- They help us apply *vectorization* in NumPy that is way faster than iterating over elements

- They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.



## 2. Parameters Of Ufuncs

- where: boolean array or condition defining where the operations should take place.

- dtype: defining the return type of elements.

- out: output array where the return value should be copied.

## 3. Vectorization: 

- Converting iterative statements into a vector based operation is called vectorization.

- It is faster as modern CPUs are optimized for such operations.


In [ ]:
import numpy as np

a = [1, 2, 3, 4]
b = [4, 5, 6, 7]
c = []

for i, j in zip(a, b):
  c.append(i + j) #this is normal python zip and append so it gives a list
print(c)


#using ufunc add()

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x,y) #this is now vectorized with help of C loops so it gives an array

print(z)

[5, 7, 9, 11]
[ 5  7  9 11]


## 2. Creating An UFunc

- To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

- The frompyfunc() method takes the following arguments:

- function - the name of the function.
- inputs - the number of input arguments (arrays).
- outputs - the number of output arrays 

In [ ]:
import numpy as np

def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1,2,3,4], [5,6,7,8]))


[6 8 10 12]


## 3. Checking If A Function Is UFunc Or Not

- Every Ufunc must return <class 'numpy.ufunc'>.

- We can check this via if statements also but we must use numpy.ufunc for this 

In [ ]:
#verifying via data type

def myadd(x,y,z):
    return x+y+z

myadd = np.frompyfunc(myadd, 3, 1) #here we establish function, input, and ouput 

print(myadd([1,2,3,4], [5,6,7,8], [9,10,11,12]))
print(type(myadd))

print(type(np.concatenate)) #it returns this since this is not an UFunc 

[15 18 21 24]
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [20]:
#verifying via class

if type(np.add) == np.ufunc:
    print("this is a ufunc")

else:
    print("this is not a ufunc")


this is a ufunc


# 2. Applying Arithmetical Ops On Arrays

- You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

- Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

- All of the discussed arithmetic functions take a where parameter in which we can specify that condition.



## 1. Addition: 

- The add() function sums the content of two arrays, and return the results in a new array.

## 2. Subtraction:

- The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

## 3. Multiplication:

- The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

## 4. Division : 

- The divide() function divides the values from one array with the values from another array, and return the results in a new array.

## 5. Power:

- The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

## 6. Remainder:

- Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

## 7. Quotient and Mod: 

- The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

## 8. Absolute Value:

- Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()



In [ ]:

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

#addition
arr3 = np.add(arr1,arr2)
print(arr3)

#subtraction
arr3 = np.subtract(arr1, arr2)
print(arr3)

#multiplication
arr3 = np.multiply(arr1, arr2)
print(arr3)

#division
arr3 = np.divide(arr1,arr2)
print(arr3)

#power
arr3 = np.power(arr1, arr2)
print(arr3)

#remainder/mod
arr3 = np.mod(arr1, arr2)
print(arr3)

#quotient/mod
arr3 = np.divmod(arr1, arr2)
print(arr3)

#absolute value
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)
print(newarr)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[1 2 3 4 5]
(array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))
[1 2 1 2 3 4]


# 3. Rounding Off Numbers

- Truncation/Fix: Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

- Rounding: The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

- Floor: The floor() function rounds off decimal to nearest lower integer.

- Ceil: The ceil() function rounds off decimal to nearest upper integer.

In [34]:
#truncation/fix
arr = np.trunc([-3.1666, 3.6667])
print(arr)


#using fix to get same results 

arr1 = np.fix([-3.1666, 3.6667])
print(arr1)

#rounding

arr2 = np.around(3.1666, 2)
print(arr2)


#floor

arr3 = np.floor([-3.1666, 3.6667])
print(arr3)

#ceil 

arr4 = np.ceil([-3.1666, 3.6667])
print(arr4)


[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


# 4. Summation

### What is the difference between addition and summation?

- Addition is done between two arguments whereas summation happens over n elements.

In [ ]:
#addition

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

arr3 = np.add(arr1, arr2)
print(arr3)


#summation 

arr4 = np.array([1, 2, 3]) #this is 6
arr5 = np.array([1, 2, 3]) #this is 6 so 6+6 = 12

arr6 = np.sum([arr4, arr5])
print(arr6)

[2 4 6]
12


## 1. Summation Over An Axis 

- If you specify axis=1, NumPy will sum the numbers in each array.

In [ ]:
#performing summation over axis=1

arr1 = np.array([1, 2, 3]) #this is 6
arr2 = np.array([1, 2, 3]) #this is 6 but it gives only along axis

arr3 = np.sum([arr1, arr2], axis=1)
print(arr3)

[6 6]


## 2. Cummultative Sum 

- Cummulative sum means partially adding the elements in array.

- E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

- Perfom partial sum with the cumsum() function.

In [40]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]
